### ISSUE TITLE
FramedTransport::Header not serialized?!

### ISSUE THREAD

**Issue by infn-ke** [EmbeddedRPC/erpc#163] opened 2021-02-12 11:56 UTC
Why is not the erpc header (`FramedTransport::Header`) serialized? E.g. do `htons` on the 16 bit members `m_messageSize` and `m_crc`.

**Comment by ierturk** [comment] 2021-02-17 12:22
I experienced problems due to lack of serialized header, and added some code to framed transport class to serialize header. I can share the code on request.

**Comment by infn-ke** [comment] 2021-02-17 12:25
Maybe you can raise a PR so that it can be included in master branch of erpc? I don't want to maintain a fix on my own.

**Comment by Hadatko** [comment] 2021-02-17 12:31
Hi, Could you  explain why you need serialize framedTransport header? Currently it is send to other side before serialized message as it contains extra data in compare with other possible transports.

**Comment by ierturk** [comment] 2021-02-17 12:47
Hi @Hadatko , using the term serialize may be wrong here. Sometimes the transferred header may be corrupted due to lack of frame and CRC. So I have to add an extra frame and CRC to check header integrity into header.

**Comment by Hadatko** [comment] 2021-02-17 12:53
So the issue is related to sending receiving message size. As second receive call is using size from first call. Sounds reasonable to me to have crc of header.

**Comment by ierturk** [comment] 2021-02-17 13:31
Yes, it is related to message size. The second side wait for message with incorrect size. So the transfer is aborted if there is a timeout for the transfer. In our particular situation, the content of message were coded as `ASCII` and added framing characters. May be the measures other than `CRC` are not needed.

**Comment by infn-ke** [comment] 2021-02-17 13:48
@Hadatko Why is it not needed to serialize and deserialize header? Representing header in network byte order would be the only way to let little-endian and big-endian exchange header before receiving the payload.

**Comment by Hadatko** [comment] 2021-02-17 14:19
So we have two issues here. Serializing header and validate header. If you can create PR for both of them it should be great ;) Thank you guys.

**Comment by Hadatko** [comment] 2023-08-28 06:26
I will take a look on theese.

**Comment by amgross** [comment] 2023-08-28 08:27
Didn't it solved enough at #276 ?
If someone want he can use htons as implementation of the endiannes agnostic defines.
Maybe we can consider add such implementation.

**Comment by amgross** [comment] 2023-08-28 08:58
https://github.com/EmbeddedRPC/erpc/blob/b3951d834d446b87e6e9a3b47dca71c36f5b37cf/erpc_c/infra/erpc_framed_transport.cpp#L128

**Comment by Hadatko** [comment] 2023-08-28 09:02
@amgross :D That is crc of next message (serialized data). But there is no check if sended header data are correct. From what i understand here we need add crcHeader into Header struct. This one will be computed from header crc and length. 
Other side then need firstly check header crc and then receive body and check body crc. This way you know that length and crc in header struct was received correctly

**Comment by amgross** [comment] 2023-08-28 10:26
The first message here talked about 'E.g. do htons on the 16 bit members m_messageSize and m_crc', so I thought we are talking on endianness issue

**Comment by amgross** [comment] 2023-08-28 11:27
I think @infn-ke (which opened the issue) talked here on endianness and @ierturk talked about length issue (which I also faced once)

**Closed** 2023-10-24 14:55 UTC
